import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Blog 👋",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="bg-white dark:bg-gray-800">{children}</body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Tailwind CSS: Dark Mode",
//   description: "Adding dark mode to our Next.js app using Tailwind CSS",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" className={inter.className}>
//       <body className="bg-white dark:bg-slate-950">{children}</body>
//     </html>
//   );
// }
